name: Deploying landing on VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Debugging
      - name: Check secrets
        run: |
          echo "VPS_IP is set: ${{ secrets.VPS_IP != '' }}"
          echo "VPS_USER is set: ${{ secrets.VPS_USER != '' }}"
          echo "VPS_PORT is set: ${{ secrets.VPS_PORT != '' }}"
          echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.VPS_PORT }} \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} \
              "echo 'SSH connection successful'"

      - name: Run updater script on VPS
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.VPS_PORT }} \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} \
              "cd /home/andromeda/docker-data/projects/landing && bash update-landing.sh"
